<?php
declare(strict_types=1);

namespace Ufo\Model;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Ufo\Component\Eloquent\Eloquent;
use Ufo\ValueObject\PayoutType;

/**
 * @property int          id
 *
 * @property float deposit
 * @property string currency
 *
 * @property string transaction_id
 * @property string payout_type
 * @property float payout_value
 * @property float payout_amount
 * @property string payout_currency
 *
 * @property string user_uid
 *
 * @property Affiliate    affiliate
 * @property AffiliateUrl affiliateUrl
 */
final class AffiliateActionLog extends Eloquent
{
    protected $table = 'affiliate_action_log';
    public $timestamps = false;

    /**
     * The name of the "created at" column.
     *
     * @var string|null
     */
    const CREATED_AT = 'created';

    /**
     * The name of the "updated at" column.
     *
     * @var string|null
     */
    const UPDATED_AT = 'updated';

    public function getId(): int
    {
        return $this->id;
    }

    public function affiliate(): BelongsTo
    {
        return $this->belongsTo(Affiliate::class, 'affiliate_id');
    }

    public function affiliateUrl(): BelongsTo
    {
        return $this->belongsTo(AffiliateUrl::class, 'url_id');
    }

    public function save(array $options = [])
    {
        if (!$this->offer_id) { // todo remove
            $this->offer_id = 1;
        }
        if (!$this->id && $this->deposit && PayoutType::PERCENT === $this->payout_type) { // todo move to service
            $this->payout_amount = $this->deposit / 100 * $this->payout_value;
            $this->payout_currency = $this->currency;
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
